# Generated by Django 4.2.29 on 2026-03-23 13:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='分类名称')),
                ('order', models.IntegerField(default=0, verbose_name='排序序号')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to=settings.AUTH_USER_MODEL, verbose_name='所属用户')),
            ],
            options={
                'verbose_name': '分类',
                'verbose_name_plural': '分类',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='对话标题')),
                ('system_prompt', models.TextField(blank=True, default='你是一个智能助手', verbose_name='系统提示词')),
                ('temperature', models.FloatField(default=0.7, verbose_name='温度参数')),
                ('top_p', models.FloatField(default=0.9, verbose_name='TopP参数')),
                ('max_tokens', models.IntegerField(default=2048, verbose_name='最大Token')),
                ('is_private', models.BooleanField(default=False, verbose_name='是否隐私对话')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '对话条目',
                'verbose_name_plural': '对话条目',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('privacy_password_hash', models.CharField(blank=True, default='', max_length=256, verbose_name='隐私密码哈希')),
                ('default_model', models.CharField(blank=True, default='minimax', max_length=50, verbose_name='默认大模型')),
                ('api_key', models.CharField(default='', max_length=256, verbose_name='api密钥')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='所属用户')),
            ],
            options={
                'verbose_name': '用户资料',
                'verbose_name_plural': '用户资料',
            },
        ),
        migrations.CreateModel(
            name='ModelConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='配置名称')),
                ('model_name', models.CharField(default='minimax', max_length=50, verbose_name='模型名称')),
                ('temperature', models.FloatField(default=0.7, verbose_name='温度参数')),
                ('top_p', models.FloatField(default=0.9, verbose_name='TopP参数')),
                ('max_tokens', models.IntegerField(default=2048, verbose_name='最大Token')),
                ('is_global', models.BooleanField(default=False, verbose_name='是否全局配置')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='model_configs', to=settings.AUTH_USER_MODEL, verbose_name='所属用户')),
            ],
            options={
                'verbose_name': '模型参数配置',
                'verbose_name_plural': '模型参数配置',
            },
        ),
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='文件夹名称')),
                ('order', models.IntegerField(default=0, verbose_name='排序序号')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='folders', to='chat.category', verbose_name='所属分类')),
                ('parent_folder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_folders', to='chat.folder', verbose_name='父文件夹')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='folders', to=settings.AUTH_USER_MODEL, verbose_name='所属用户')),
            ],
            options={
                'verbose_name': '文件夹',
                'verbose_name_plural': '文件夹',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', '用户'), ('assistant', 'AI助手')], max_length=20, verbose_name='消息角色')),
                ('content', models.TextField(verbose_name='消息内容')),
                ('is_stream', models.BooleanField(default=True, verbose_name='是否流式输出')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='发送时间')),
                ('chat_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.chatentry', verbose_name='所属对话')),
            ],
            options={
                'verbose_name': '对话消息',
                'verbose_name_plural': '对话消息',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddField(
            model_name='chatentry',
            name='folder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_entries', to='chat.folder', verbose_name='所属文件夹'),
        ),
        migrations.AddField(
            model_name='chatentry',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_entries', to=settings.AUTH_USER_MODEL, verbose_name='所属用户'),
        ),
    ]
