# Generated by Django 4.2.29 on 2026-03-28 11:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatentry',
            name='max_tokens',
            field=models.IntegerField(default=2048, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(8192)], verbose_name='最大Token'),
        ),
        migrations.AlterField(
            model_name='chatentry',
            name='temperature',
            field=models.FloatField(default=0.7, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)], verbose_name='温度参数'),
        ),
        migrations.AlterField(
            model_name='chatentry',
            name='top_p',
            field=models.FloatField(default=0.9, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)], verbose_name='TopP参数'),
        ),
        migrations.AlterField(
            model_name='modelconfig',
            name='max_tokens',
            field=models.IntegerField(default=2048, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(8192)], verbose_name='最大Token'),
        ),
        migrations.AlterField(
            model_name='modelconfig',
            name='model_name',
            field=models.CharField(default='qwen-plus', max_length=50, verbose_name='模型名称'),
        ),
        migrations.AlterField(
            model_name='modelconfig',
            name='temperature',
            field=models.FloatField(default=0.7, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)], verbose_name='温度参数'),
        ),
        migrations.AlterField(
            model_name='modelconfig',
            name='top_p',
            field=models.FloatField(default=0.9, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)], verbose_name='TopP参数'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='default_model',
            field=models.CharField(blank=True, default='qwen-plus', max_length=50, verbose_name='默认大模型'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='privacy_password_hash',
            field=models.CharField(blank=True, default='', max_length=256, verbose_name='隐私密码'),
        ),
    ]
