# Generated by Django 4.2.29 on 2026-03-29 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_chatentry_max_tokens_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatentry',
            name='keywords_string',
            field=models.CharField(blank=True, editable=False, max_length=500),
        ),
    ]
