# Generated by Django 4.2.29 on 2026-03-29 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_chatentry_keywords_string'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='api_key',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='_api_key_encrypted',
            field=models.CharField(default='', max_length=512, verbose_name='API密钥密文'),
        ),
    ]
