# Generated by Django 4.2.29 on 2026-03-30 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_remove_userprofile_api_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatentry',
            name='description',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='对话简介'),
        ),
    ]
